import { sortFindings, SEVERITY_RANK } from '../scoring.js';

const SEV_ICON = { critical: '🟥 CRITICAL', serious: '🟧 SERIOUS', moderate: '🟨 MODERATE', minor: '⬜ MINOR', info: 'ℹ️ INFO' };
const CAT_LABEL = {
  performance: 'Performance & Core Web Vitals',
  accessibility: 'Accessibility (WCAG 2.1 AA)',
  seo: 'SEO & Discoverability',
  bestPractices: 'Security & Best Practices',
  responsive: 'Responsive / Mobile',
  motion: 'Motion & Animation',
  stress: 'Load & Stress',
};

function bar(score) {
  if (score == null) return 'n/a';
  const filled = Math.round(score / 10);
  return `${'█'.repeat(filled)}${'░'.repeat(10 - filled)} ${score}/100 (${gradeOf(score)})`;
}
function gradeOf(s) { return s >= 90 ? 'A' : s >= 80 ? 'B' : s >= 70 ? 'C' : s >= 60 ? 'D' : 'F'; }

export function renderMarkdown(result) {
  const { url, goal, verdict, categories, allFindings, startedAt, durationMs } = result;
  const L = [];
  L.push(`# 🧪 webqa-agent report`);
  L.push('');
  L.push(`**URL:** ${url}  `);
  L.push(`**Goal:** ${goal.label} (\`${goal.key}\`)  `);
  L.push(`**Date:** ${startedAt}  `);
  L.push(`**Scan time:** ${(durationMs / 1000).toFixed(1)}s`);
  L.push('');
  L.push('## Verdict');
  L.push('');
  L.push(`### Overall: ${verdict.overall}/100 — Grade ${verdict.grade}`);
  L.push('');
  L.push(verdict.worldClass
    ? '> ✅ **World-class.** This site clears the global bar for its category. Keep it there.'
    : '> ⚠️ **Not yet world-class.** Address the findings below — start with 🟥 CRITICAL and 🟧 SERIOUS.');
  if (verdict.failedFloors.length) {
    L.push('>');
    L.push('> Blocking category floors not met: ' +
      verdict.failedFloors.map((f) => `**${CAT_LABEL[f.key] || f.key}** ${f.score} (needs ${f.floor})`).join(', '));
  }
  L.push('');
  L.push('## Scorecard');
  L.push('');
  L.push('| Category | Score |');
  L.push('|---|---|');
  for (const [key, cat] of Object.entries(categories)) {
    if (!cat) continue;
    L.push(`| ${CAT_LABEL[key] || key} | \`${bar(cat.score)}\` |`);
  }
  L.push('');

  // Top priorities across all categories.
  const sorted = sortFindings(allFindings.filter((f) => f.severity !== 'info'));
  const top = sorted.slice(0, 8);
  if (top.length) {
    L.push('## 🎯 Top priorities (fix these first)');
    L.push('');
    top.forEach((f, i) => {
      L.push(`${i + 1}. **[${(f.severity || '').toUpperCase()}] ${f.title}** — _${CAT_LABEL[f.category] || f.category}_`);
      L.push(`   ↳ ${f.fix.split('\n')[0]}`);
    });
    L.push('');
  }

  // Full breakdown per category.
  L.push('## Full findings');
  L.push('');
  const byCat = {};
  for (const f of allFindings) (byCat[f.category] ||= []).push(f);
  for (const key of Object.keys(CAT_LABEL)) {
    const cat = categories[key];
    if (!cat) continue;
    L.push(`### ${CAT_LABEL[key]} — ${cat.score == null ? 'n/a' : cat.score + '/100'}`);
    L.push('');
    if (key === 'performance' && cat.measured) {
      L.push('| Metric | Value |');
      L.push('|---|---|');
      const m = cat.measured;
      L.push(`| LCP | ${m.lcp} ms |`);
      L.push(`| CLS | ${m.cls} |`);
      L.push(`| Main-thread blocking | ${m.inpProxy} ms |`);
      L.push(`| FCP | ${m.fcp} ms |`);
      L.push(`| TTFB | ${m.ttfb} ms |`);
      L.push(`| Page weight | ${(m.weightKb / 1024).toFixed(2)} MB |`);
      L.push(`| Requests | ${m.requests} |`);
      L.push('');
    }
    if (key === 'stress' && cat.measured) {
      const m = cat.measured;
      L.push(`Load: **${m.requests} requests @ concurrency ${m.concurrency}** · ${m.rps} req/s`);
      L.push('');
      L.push('| p50 | p95 | p99 | max | errors |');
      L.push('|---|---|---|---|---|');
      L.push(`| ${m.p50}ms | ${m.p95}ms | ${m.p99}ms | ${m.max}ms | ${m.errorRate}% |`);
      L.push('');
    }
    const findings = sortFindings(byCat[key] || []);
    if (!findings.length) { L.push('_No issues found. ✅_'); L.push(''); continue; }
    for (const f of findings) {
      L.push(`- **${SEV_ICON[f.severity] || f.severity}** — ${f.title}`);
      if (f.detail) L.push(`  - ${f.detail}`);
      if (f.fix) L.push(`  - **Fix:** ${f.fix.replace(/\n/g, '\n    ')}`);
    }
    L.push('');
  }

  L.push('---');
  L.push('');
  L.push('_Generated by [webqa-agent](https://github.com/farisradir-blip/webqa-agent) — your autonomous website QA engineer._');
  return L.join('\n');
}
